import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {
    geistMono,
    geistSans,
    orbitron,
    pressStart2P,
} from "@/components/fonts";
import PokeNavbarHeroResponsive from "@/components/navbar/PokeNavbarHeroResponsive";

export const metadata: Metadata = {
    title: "Agun Pakhi",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${pressStart2P.variable} antialiased bg-black`}
            >
            <nav className="relative z-50">
                <PokeNavbarHeroResponsive />
            </nav>

            <main className="relative z-0">
            {children}
            </main>
        </body>
        </html>
    );
}
