import type { Metadata } from "next"
import "./globals.css"
import {
  geistMono,
  geistSans,
  orbitron,
  pressStart2P,
} from "@/components/fonts"
import AppShell from "@/components/AppShell"
import { FaDiscord, FaGithub, FaInstagram, FaLinkedin } from "react-icons/fa6"

export const metadata: Metadata = {
  title: "Agun Pakhi",
  description: "Generated by create next app",
}

export default function RootLayout({
  iconSize = 26,
  children,
}: {
  iconSize?: number;
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${orbitron.variable}
          ${pressStart2P.variable}
          antialiased bg-black
        `}
      >
        <AppShell>{children}</AppShell>
      </body>
    </html>
  )
}
